# Source: acme/templates/cert-manager-prod-clusterissuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    meta.helm.sh/release-name: 'acme-jx'
  labels:
    gitops.jenkins-x.io/pipeline: 'cluster'
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "ops@entando.com"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - selector:
          dnsNames:
            - "*.jx.entando.io"
            - "jx.entando.io"
        # ACME DNS-01 provider configurations
        dns01:
          azureDNS:
            subscriptionID: 3968a4ee-a20a-4ff2-9fdb-27ecc0f62414
            resourceGroupName: rg-dns-jenkins-x-3
            hostedZoneName: jx.entando.io
