# Source: acme/templates/cert-manager-staging-certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "tls-jx-entando-io-s"
  labels:
    jenkins.io/letsencrypt-service: staging
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'acme-jx'
  namespace: jx
spec:
  secretName: "tls-jx-entando-io-s"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.jx.entando.io"
  dnsNames:
    - "*.jx.entando.io"
    - "jx.entando.io"
