apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        entando-k8s/entando-k8s-operator-common: true
        entando-k8s/jx3-azure-akv: true
        pietrangelo/jx-rust-http: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        entando-k8s/entando-k8s-operator-common: merge
        entando-k8s/jx3-azure-akv: merge
        pietrangelo/jx-rust-http: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - entando-k8s/jx3-azure-akv
        - entando-k8s/entando-k8s-operator-common
        - pietrangelo/jx-rust-http
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - entando-k8s/jx3-azure-akv
        - entando-k8s/entando-k8s-operator-common
        - pietrangelo/jx-rust-http
      target_url: http://lighthouse-jx.jx.entando.io/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
