apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: pietrangelo
    provider: github
    repository: jx-rust-http
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: pietrangelo-jx-rust-http
  namespace: jx
spec:
  httpCloneURL: https://github.com/pietrangelo/jx-rust-http.git
  org: pietrangelo
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: jx-rust-http
  scheduler:
    kind: ""
    name: in-repo
  url: https://github.com/pietrangelo/jx-rust-http
