# Source: external-dns/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: external-dns
  labels:
    app.kubernetes.io/name: external-dns
    helm.sh/chart: external-dns-5.0.0
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: 'external-dns'
  namespace: jx
type: Opaque
data:
  azure.json: "ewogICJ0ZW5hbnRJZCI6ICJmNjQ2MjY5Zi1lYzllLTQ5MDgtOTYzMC05MDAxNWQwNWI0NjIiLAogICJzdWJzY3JpcHRpb25JZCI6ICIzOTY4YTRlZS1hMjBhLTRmZjItOWZkYi0yN2VjYzBmNjI0MTQiLAogICJyZXNvdXJjZUdyb3VwIjogInJnLWRucy1qZW5raW5zLXgtMyIsCiAgInVzZU1hbmFnZWRJZGVudGl0eUV4dGVuc2lvbiI6IHRydWUKfQo="
