# Source: external-dns/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: jx
  labels:
    app.kubernetes.io/name: external-dns
    helm.sh/chart: external-dns-5.0.0
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/managed-by: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'external-dns'
    wave.pusher.com/update-on-config-change: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns
      app.kubernetes.io/instance: external-dns
  template:
    metadata:
      labels:
        app.kubernetes.io/name: external-dns
        helm.sh/chart: external-dns-5.0.0
        app.kubernetes.io/instance: external-dns
        app.kubernetes.io/managed-by: Helm
      annotations:
        prometheus.io/port: "7979"
        prometheus.io/scrape: "true"
        checksum/secret: 9239cbe934c2cc3b0ecc7ceb1442538e574aa6f94750a5a6ea3c963ad83038af
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      affinity:
        podAffinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: external-dns
                    app.kubernetes.io/instance: external-dns
                namespaces:
                  - "jx"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: "docker.io/bitnami/external-dns:0.8.0-debian-10-r0"
          imagePullPolicy: "IfNotPresent"
          args:
            # Generic arguments
            - --log-level=info
            - --log-format=text
            - --domain-filter=jx.entando.io
            - --policy=sync
            - --provider=azure
            - --registry=txt
            - --interval=1m
            - --source=ingress
            # Azure Arguments
            - --azure-resource-group=rg-dns-jenkins-x-3
          env:
          ports:
            - name: http
              containerPort: 7979
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
            # Azure mountPath(s)
            - name: azure-config-file
              mountPath: /etc/kubernetes/
              readOnly: true
      volumes:
        # Azure volume(s)
        - name: azure-config-file
          secret:
            secretName: external-dns
